version: '2.0'
services:
  web:
    image: 'jwilder/whoami'
    ports: 
      - 8000
  lb:
    image: 'dockercloud/haproxy'
    links:
      - web
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock